describe('Add Contact Tests', () => {
  it('Can add new contact', () => {

    let random = Math.floor(Math.random() * 1000)

    cy.visit('https://thinking-tester-contact-list.herokuapp.com/')
    cy.get('#email').type('hartzart@ahrixthinh.net')
    cy.get('#password').type('cypressproject')
    cy.get('#submit').click()
    cy.get('#add-contact').click()
    cy.get('#firstName').type('Test' + random)
    cy.get('#lastName').type('User')
    cy.get('#birthdate').type('1990-01-01')
    cy.get('#email').type('hartzart@ahrixthinh.net')
    cy.get('#phone').type('1234567890')
    cy.get('#street1').type('123 Test St')
    cy.get('#street2').type('Apt 456')
    cy.get('#city').type('Test City')
    cy.get('#stateProvince').type('Test State')
    cy.get('#postalCode').type('12345')
    cy.get('#country').type('Test Country')
    cy.get('#submit').click()

    //[2]cy.contains('Test' + random + ' User').click()
    cy.get('#delete').click()
    cy.on('window:confirm', () => true) // Automatically confirm the delete dialog
    //cy.contains('Test' + random + ' User').should('not.exist')

    //[1]cy.contains('Test' + random + ' User').click()
    // cy.get('#firstName').should('contain', `Test${random}`) 
    // cy.get('#lastName').should('contain', `User`) 
    // cy.get('#birthdate').should('contain', `1990-01-01`)
    // cy.get('#email').should('contain', `hartzart@ahrixthinh.net`)
    // cy.get('#phone').should('contain', `1234567890`)
    // cy.get('#street1').should('contain', `123 Test St`)
    // cy.get('#street2').should('contain', `Apt 456`)
    // cy.get('#city').should('contain', `Test City`)
    // cy.get('#stateProvince').should('contain', `Test State`)
    // cy.get('#postalCode').should('contain', `12345`)
    // cy.get('#country').should('contain', `Test Country`)
  })
})